name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore './KittyManagementService/'
    - name: Build
      run: dotnet build './KittyManagementService/' --configuration Release --no-restore
    - name: Test
      run: dotnet test './KittyManagementService/' --no-restore --verbosity normal
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        path: './KittyManagementService/KittyManagementService/bin/Release/netcoreapp3.1/*'
    - name: Buildah Action
      uses: redhat-actions/buildah-build@v1
      with:
        image: docker.io/cyberic/kms
        tag: 1.0.0
