name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install Dependencies
      run: dotnet restore './KittyManagementService/'
    - name: Build Application
      run: dotnet build './KittyManagementService/' --configuration Release --no-restore
    - name: Test Application
      run: dotnet test './KittyManagementService/' --no-restore --verbosity normal
    - name: Coverlet SAST
      uses: b3b00/coverlet-action@1.0.96
      with:
        testProject: './KittyManagementService/KittyManagementService.csproj'
        output: 'json.info'
        exclude: '[program]*,[test]test.*'        
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: './KittyManagementService/KittyManagementService/bin/Release/netcoreapp3.1/*'
