name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-artifacts:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install Dependencies
      run: dotnet restore './KittyManagementService/'
    - name: Build Application
      run: dotnet build './KittyManagementService/' --configuration Release --no-restore
    - name: Test Application
      run: dotnet test './KittyManagementService/' --no-restore --verbosity normal
    - name: Install snapd 
      run:  sudo -S apt install snapd -y
    - name: Install docker 
      run: sudo -S snap install docker
    - name: sleep to wait for docker to finsh init 
      run: sleep 15
    - name: Docker build
      run: docker build -t KMS:1.0 './KittyManagementService/KittyManagementService/'
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: './KittyManagementService/KittyManagementService/bin/Release/netcoreapp3.1/*'